# Generated by Django 4.0 on 2022-01-04 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managing_tasks', to='user.myuser'),
        ),
        migrations.AddField(
            model_name='task',
            name='member',
            field=models.ManyToManyField(related_name='involved_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
