# Generated by Django 4.0 on 2022-01-04 06:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0002_task_manager_task_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='member',
            field=models.ManyToManyField(related_name='involving_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
