# Generated by Django 4.0 on 2022-01-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Initial', 'Initial'), ('On-going', 'On-going'), ('Closed', 'Closed')], default='On-going', max_length=20),
            preserve_default=False,
        ),
    ]
